version: '2'
services:
    to-test-flowchart:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: to-test-flowchart
        restart: always
        volumes:
         - ./:/flowchart
        tty: true
